### PR TITLE
Add districts and contacts for Aurora, CO

### PR DESCRIPTION
**Pull request by dallasjc**
This pr adds coordinates and contact info for Aurora, CO districts and elected officials

### CODE REVIEW

**Comment by alexmingoia** [comment]
The districts have the wrong city in their name, and the points aren't geographic.

The shapes need to be coordinates in EPSG:4396 WGS 84 (they need to be standard lat/lon)

**Comment by dallasjc** [comment]
Good catch! I've fixed the city names.
That said, I have no idea what's wrong with the shapes. The coordinates appear
similar in the files, are you getting a report it's in a different format?
Is there a tool I can use to test each set of coordinates to make sure they're
correct? I think I merged the city council wards in order to get the city
boundaries for the at-large districts, I'm wondering if those are the specific
problem.  





On Thu, Aug 22, 2019 8:37 PM, Alex Mingoia notifications@github.com  wrote:
The districts have the wrong city in their name, and the points aren't
geographic.

The shapes need to be coordinates in EPSG:4396 WGS 84 (they need to be standard
lat/lon)

**Comment by alexmingoia** [comment]
If you look at the points of the shape, they're not WGS84 coordinates, but part of some other coordinate system. `[3273232.2985863835,1737734.3878444284]` is not a WGS84 latitude/longitude. Those numbers don't map to anywhere on the globe: https://en.wikipedia.org/wiki/World_Geodetic_System

If they're part of some other coordinate system then you'll have to figure out how to correctly project them. There's a lot of coordinate systems, but as far as geographic data goes the international standard is WGS84, which is the coordinate system being used wherever you see lat/lon usually.

**Comment by dallasjc** [comment]
Gotcha, thanks. I'll try to figure out how to convert it  





On Fri, Aug 23, 2019 8:30 PM, Alex Mingoia notifications@github.com  wrote:
If you look at the points of the shape, they're clearly not WGS84 coordinates,
but part of some other coordinate system. 
[3273232.2985863835,1737734.3878444284]  is not a WGS84 latitude/longitude.
Those numbers don't map to anywhere on the globe: 
https://en.wikipedia.org/wiki/World_Geodetic_System

**Comment by alexmingoia** [comment]
Where are the shapefiles for Aurora coming from?

**Comment by dallasjc** [comment]
https://data-auroraco.opendata.arcgis.com/datasets/city-council-wards
It's not just Aurora, I have shapefiles from several other localities that
default to something other than long/lat  





On Fri, Aug 23, 2019 9:30 PM, Alex Mingoia notifications@github.com  wrote:
Where are the shapefiles for Aurora coming from?

**Comment by alexmingoia** [comment]
Merged.

**Pull request closed without merging**
