### PR TITLE
Update Madison, WI legislators

### PR DESCRIPTION
**Pull request by dallasjc**
Added the json file for Madison, WI with district info, names, images, and emails.

Converted shape file to geojson

The geojson file I was given had different spacing than the Dane County one, so I used the spacing used in the geojson file

### CODE REVIEW

**Comment by alexmingoia** [comment]
This looks mostly correct, but the JSON isn't valid. It has typos/invalid characters. Run it through https://jsonlint.com/ and you'll see.

**Comment by dallasjc** [comment]
Oops, thanks - think I fixed it (it says valid JSON now)  





On Mon, Jul 22, 2019 8:15 PM, Alex Mingoia notifications@github.com  wrote:
This looks mostly correct, but the JSON isn't valid. It's got typos/invalid
characters. Run it through https://jsonlint.com/  and you'll see.

**Comment by alexmingoia** [comment]
Okay everything is good but there's some legislators with a `-` in the username, which we don't allow. Can you fix that and I can merge? I would fix but you're working on your own fork. I can't push to your branch.

I've already imported this in production, so liquid.us should show correct Alders. I have not confirmed, however.

**Comment by dallasjc** [comment]
Just pushed the fix to get rid of the hyphens. Thanks for your help!  





On Tue, Jul 23, 2019 12:21 AM, Alex Mingoia notifications@github.com  wrote:
Okay everything is good but there's some legislators with a -  in the username,
which we don't allow. Can you fix that and I can merge? I would fix but you're
working on your own fork. I can't push to your branch.

I've already imported this in production, so liquid.us should show correct
Alders, but I have not confirmed.

**Pull request merged**
