### PR TITLE
Add Dane County district files

### PR DESCRIPTION
**Pull request by dallasjc**
Adds legislator info and districts for Dane County, WI

### CODE REVIEW

**Comment by alexmingoia** [comment]
I'm not sure there's any utility in having this on GitHub before I create a standardized format for districts and the associated office/legislature information, and hooking it up to read from this GitHub repo. Then you would need to use some sort of shapefile editor to format everything correctly to fit a standard format.

**Comment by dsernst** [comment]
Super valuable to see the prep process in public, for others (incl myself) to learn from

**Comment by alexmingoia** [comment]
I imported the Dane County reps. We now have a standard JSON format to import legislatures/districts/legislators. See the readme and dane county JSON I committed.

There are various tools for editing shapefiles and outputting GeoJSON, so in the future put everything in that format and I can hook up a script to automatically sync legislature data from this repo.

**Comment by dsernst** [comment]
Awesome. Thx ✌️

**Pull request closed without merging**
